travis:
  secure:
    BINSTAR_TOKEN: G2kEyIkqQsSJKP8xZMVM3NdlGQKZJt4VKlueERAbno6Q6pVT3clSGrsZKYusj8deec12bL1l34+LEUtYMIw4IOYkcO9MIzyWwy06kbHODGbiwZ2zZIsiVhyqAjpGG3DTboaghrQK5lzjKHuwJfPRO9L0hOqYg7yd7SAtm9vCVCptnPeFW3qoeACzB7DpFrmLpaBM/2GBXYceBMYOrebthAIPCiIbzXKKlo7RqM7gy0APMsz7kn82HqaBaSRKBKQzyUjemfROsFJ10HuGE7dY2ZaOfTA0Wx2YYtXY37wi6uqECrmH2CONatWB6uZevR65IeXfTOM3ZXsUKjlSpstHFM503JCpEwx7AHwnbg3IK/tIZ3weCebjAK4SEBhLa9mxZ1bJ1SecdRmbefWyjB5PJK3l14TBJLpmxlrs2jONBNuEppqMh8VNwX0a4XY6sB9HNLMxvUOhYn4P9fiw4q3c55uLdd18BwyU1ZYzz/0bf4dzfqhyu/DhI7T6wsjSncdPbhxwW2WNS374fKIG/PDE/MNDh3lilqTkA6VBWkIxptVHAVm6VTKwNrJsGNcYA8ioFurSh7KjVx0HcoMZ9rsmIOhG3emffwcCoIxY8Cap2nyohOTue1NlVXkSpE3j3aDNQpc9t8SNF4OQBq+XrtbLdfC45dzZ8D+TyF8Ve40WjN8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
